language: node_js
node_js:
  - "8.11.1"
before_script:
  - yarn add codecov
after_success:
  - npm run coverage
after_script:
  - nyc report --reporter=text-lcov | coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
services:
  - postgresql
addons:
  postgresql: "9.6"
